apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ashiorid

resources:
  - prometheus.yaml
  - grafana.yaml

commonLabels:
  component: monitoring
  project: ashiorid-ai-manager
  managed-by: kustomize
