apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ashiorid

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml

commonLabels:
  app: lore-rag
  service: lore-rag-service
  project: ashiorid-ai-manager
