apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ashiorid

resources:
  - namespace.yaml
  - postgres.yaml
  - redis.yaml
  - qdrant.yaml
  - traefik.yaml

commonLabels:
  project: ashiorid-ai-manager
  managed-by: kustomize
